package io.agrest.it.fixture.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.agrest.it.fixture.cayenne.E26;

/**
 * Class _E23 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E23 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> EXPOSED_ID = Property.create("exposedId", Integer.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<E26>> E26S = Property.create("e26s", List.class);

    public void setExposedId(Integer exposedId) {
        writeProperty("exposedId", exposedId);
    }
    public Integer getExposedId() {
        return (Integer)readProperty("exposedId");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToE26s(E26 obj) {
        addToManyTarget("e26s", obj, true);
    }
    public void removeFromE26s(E26 obj) {
        removeToManyTarget("e26s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E26> getE26s() {
        return (List<E26>)readProperty("e26s");
    }


}
