=== Configure and run API generation
There is an example of the Maven plugin configuration:
[source, XML]
----
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>3.0.2</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/bookstore-api.yaml</inputSpec>
                <generatorName>io.swagger.codegen.languages.AgServerCodegen</generatorName>
                <output>${project.basedir}</output>
                <apiPackage>org.example.agrest</apiPackage>
                <modelPackage>org.example.agrest.persistente</modelPackage>
                <invokerPackage>org.example.agrest</invokerPackage>
                <generateModels>false</generateModels>
                <skipOverwrite>false</skipOverwrite>
            </configuration>
        </execution>
    </executions>

    <dependencies>
        <dependency>
            <groupId>io.agrest.openapi</groupId>
            <artifactId>agrest-openapi-designfirst</artifactId>
            <version>3.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</plugin>
----
[#inputSpec]
===== <inputSpec>
Points to your API definition in `.yaml` or `.json` formats.

[#generatorName]
===== <generatorName>
Sets the Agrest custom code generator.

[#output]
===== <output>
Sets the output catalog for all generated items.

[#apiPackage]
===== <apiPackage>
Contains full package name of resource implementation classes to be generated.

[#modelPackage]
===== <modelPackage>
Contains full package name of model classes.
If <<generateModels>> is set to `true`, the POJO stubs of models will be generated.
Otherwise, existing model classes from this package will be used.

[#generateModels]
===== <generateModels>
Generates POJO of models or uses existing ones.

[#skipOverwrite]
===== <skipOverwrite>
If it is set to `false`, all generated files will be overwritten each time during `mvn clean install`.
So, if you are planning to customize the generated API implementation, this parameter should be set to `true`.


==== Run the Application

As we mentioned in the chapter <<Building and running>> the Application is run by command `mvn jetty:run`.
After the Jetty server starts, the following `curl` commands can be used for the API testing:

```
curl -i -X GET 'http://localhost:8080/api/v1/category'
```

```
curl -i -X POST -H 'Content-Type: application/json' 'http://localhost:8080/api/v1/category'  -d '{"id":"1","name":"Science Fiction"}'
```

Please, pay attention that the `POST` command has to contain the `Content-Type` parameter according to the annotation
of the 'create' method of the `CategoryResource` class.