=== Configure and run the API generation
There is an example of the maven plugin configuration:
[source, XML]
----
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>3.0.2</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/bookstore-api.yaml</inputSpec>
                <generatorName>io.swagger.codegen.languages.AgServerCodegen</generatorName>
                <output>${project.basedir}</output>
                <apiPackage>org.example.agrest</apiPackage>
                <modelPackage>org.example.agrest.persistente</modelPackage>
                <invokerPackage>org.example.agrest</invokerPackage>
                <generateModels>false</generateModels>
                <skipOverwrite>false</skipOverwrite>
            </configuration>
        </execution>
    </executions>

    <dependencies>
        <dependency>
            <groupId>org.example.agrest</groupId>
            <artifactId>bookstore</artifactId>
            <version>${version}</version>
        </dependency>
    </dependencies>
</plugin>
----
[#inputSpec]
==== <inputSpec>
Points to your API definition in `.yaml` or `.json` formats.

[#generatorName]
==== <generatorName>
Sets the AgREST custom code generator.

[#output]
==== <output>
Sets the output catalog for all generated items.

[#apiPackage]
==== <apiPackage>
Contains full package name of resource implementation classes to be generated.

[#modelPackage]
==== <modelPackage>
Contains full package name of model classes.
If set <<generateModels>> true, the POJO stubs of models will be generated.
Otherwise, will be used existing model classes from this package.

[#generateModels]
==== <generateModels>
Generates POJO of models or uses existing ones.

[#skipOverwrite]
==== <skipOverwrite>
If it is set in `false`, all generated files will be overwritten each time during `mvn clean install`.
So, if you are planning to customize the generated API implementation, this parameter should be set in `true`.