=== Setting up the environment

In this chapter, we check that you already have installed an Agrest-based application that can be used to demonstrate the Design-First approach.

==== Prerequisites
Set up and build an application example from previous chapter <<Create a Simple `Agrest` App>>.
You can either follow a step-by-step process to create an application from scratch or get a ready-made application from
GitHub https://github.com/agrestio/agrest-bookstore-example[Bookstore app]

==== Prepare the Bookstore application
As we described above, the Design-First approach means the API specification comes first, and the code comes second.

So, we have to remove from the application classes that defined API resources.
In our case it is `CategoryResource.java` we have created manually.
Later all our API resources will be generated from `.yaml` definition automatically according to
the Design-First approach.

Then update the `pom.xml`.

Add the `openapi-generator-maven-plugin` plugin and appropriate settings.
For more details, please refer tothe next section <<Configure and run API generation>>

[source, xml]
----
<plugin>
    <groupId>org.openapitools</groupId>
    <artifactId>openapi-generator-maven-plugin</artifactId>
    <version>3.0.2</version>
    <executions>
        <execution>
            <goals>
                <goal>generate</goal>
            </goals>
            <configuration>
                <inputSpec>${project.basedir}/src/main/resources/bookstore-api.yaml</inputSpec>
                <generatorName>io.swagger.codegen.languages.AgServerCodegen</generatorName>
                <output>${project.basedir}</output>
                <apiPackage>org.example.agrest</apiPackage>
                <modelPackage>org.example.agrest.persistent</modelPackage>
                <invokerPackage>org.example.agrest</invokerPackage>
                <generateModels>false</generateModels>
                <skipOverwrite>false</skipOverwrite>
            </configuration>
        </execution>
    </executions>

    <dependencies>
        <dependency>
            <groupId>io.agrest.openapi</groupId>
            <artifactId>agrest-openapi-designfirst</artifactId>
            <version>3.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</plugin>
----

==== The resulting application

The final application that implements Design-First approach is available on GitHub at:
https://github.com/agrestio/agrest-openapi-designfirst-bookstore-example[Bookstore Design-first app]