/* Generated By:JavaCC: Do not edit this line. AgExpressionParserVisitor.java Version 7.0.11 */
package io.agrest.exp.parser;

public interface AgExpressionParserVisitor<T>
{
  public T visit(SimpleNode node, T data);
  public T visit(ExpOr node, T data);
  public T visit(ExpAnd node, T data);
  public T visit(ExpNot node, T data);
  public T visit(ExpTrue node, T data);
  public T visit(ExpFalse node, T data);
  public T visit(ExpEqual node, T data);
  public T visit(ExpNotEqual node, T data);
  public T visit(ExpLessOrEqual node, T data);
  public T visit(ExpLess node, T data);
  public T visit(ExpGreater node, T data);
  public T visit(ExpGreaterOrEqual node, T data);
  public T visit(ExpLike node, T data);
  public T visit(ExpLikeIgnoreCase node, T data);
  public T visit(ExpIn node, T data);
  public T visit(ExpBetween node, T data);
  public T visit(ExpNotLike node, T data);
  public T visit(ExpNotLikeIgnoreCase node, T data);
  public T visit(ExpNotIn node, T data);
  public T visit(ExpNotBetween node, T data);
  public T visit(ExpScalarList node, T data);
  public T visit(ExpScalar node, T data);
  public T visit(ExpBitwiseOr node, T data);
  public T visit(ExpBitwiseXor node, T data);
  public T visit(ExpBitwiseAnd node, T data);
  public T visit(ExpBitwiseLeftShift node, T data);
  public T visit(ExpBitwiseRightShift node, T data);
  public T visit(ExpAdd node, T data);
  public T visit(ExpSubtract node, T data);
  public T visit(ExpMultiply node, T data);
  public T visit(ExpDivide node, T data);
  public T visit(ExpBitwiseNot node, T data);
  public T visit(ExpNegate node, T data);
  public T visit(ExpConcat node, T data);
  public T visit(ExpSubstring node, T data);
  public T visit(ExpTrim node, T data);
  public T visit(ExpLower node, T data);
  public T visit(ExpUpper node, T data);
  public T visit(ExpLength node, T data);
  public T visit(ExpLocate node, T data);
  public T visit(ExpAbs node, T data);
  public T visit(ExpSqrt node, T data);
  public T visit(ExpMod node, T data);
  public T visit(ExpCurrentDate node, T data);
  public T visit(ExpCurrentTime node, T data);
  public T visit(ExpCurrentTimestamp node, T data);
  public T visit(ExpExtract node, T data);
  public T visit(ExpNamedParameter node, T data);
  public T visit(ExpPath node, T data);
}
/* JavaCC - OriginalChecksum=07bf064c3b4fb526a1f18cfe68cf8d9d (do not edit this line) */
