/* Generated By:JJTree&JavaCC: Do not edit this line. AgExpressionParserConstants.java */
package io.agrest.exp.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface AgExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int NULL = 34;
  /** RegularExpression Id. */
  int TRUE = 35;
  /** RegularExpression Id. */
  int FALSE = 36;
  /** RegularExpression Id. */
  int CONCAT = 37;
  /** RegularExpression Id. */
  int SUBSTRING = 38;
  /** RegularExpression Id. */
  int TRIM = 39;
  /** RegularExpression Id. */
  int LOWER = 40;
  /** RegularExpression Id. */
  int UPPER = 41;
  /** RegularExpression Id. */
  int LENGTH = 42;
  /** RegularExpression Id. */
  int LOCATE = 43;
  /** RegularExpression Id. */
  int ABS = 44;
  /** RegularExpression Id. */
  int SQRT = 45;
  /** RegularExpression Id. */
  int MOD = 46;
  /** RegularExpression Id. */
  int CURRENT_DATE = 47;
  /** RegularExpression Id. */
  int CURRENT_TIME = 48;
  /** RegularExpression Id. */
  int CURRENT_TIMESTAMP = 49;
  /** RegularExpression Id. */
  int YEAR = 50;
  /** RegularExpression Id. */
  int MONTH = 51;
  /** RegularExpression Id. */
  int WEEK = 52;
  /** RegularExpression Id. */
  int DAY_OF_YEAR = 53;
  /** RegularExpression Id. */
  int DAY = 54;
  /** RegularExpression Id. */
  int DAY_OF_MONTH = 55;
  /** RegularExpression Id. */
  int DAY_OF_WEEK = 56;
  /** RegularExpression Id. */
  int HOUR = 57;
  /** RegularExpression Id. */
  int MINUTE = 58;
  /** RegularExpression Id. */
  int SECOND = 59;
  /** RegularExpression Id. */
  int PROPERTY_PATH = 61;
  /** RegularExpression Id. */
  int IDENTIFIER = 62;
  /** RegularExpression Id. */
  int LETTER = 63;
  /** RegularExpression Id. */
  int DIGIT = 64;
  /** RegularExpression Id. */
  int DOLLAR_SIGN = 65;
  /** RegularExpression Id. */
  int ESC = 68;
  /** RegularExpression Id. */
  int SINGLE_QUOTED_STRING = 70;
  /** RegularExpression Id. */
  int STRING_ESC = 71;
  /** RegularExpression Id. */
  int DOUBLE_QUOTED_STRING = 73;
  /** RegularExpression Id. */
  int INT_LITERAL = 74;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 75;
  /** RegularExpression Id. */
  int DEC_FLT = 76;
  /** RegularExpression Id. */
  int DEC_DIGITS = 77;
  /** RegularExpression Id. */
  int EXPONENT = 78;
  /** RegularExpression Id. */
  int FLT_SUFF = 79;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int WithinSingleQuoteLiteral = 1;
  /** Lexical state. */
  int WithinDoubleQuoteLiteral = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"or\"",
    "\"and\"",
    "\"not\"",
    "\"!\"",
    "\"=\"",
    "\"==\"",
    "\"!=\"",
    "\"<>\"",
    "\"<=\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"like\"",
    "\"likeIgnoreCase\"",
    "\"in\"",
    "\"(\"",
    "\")\"",
    "\"between\"",
    "\",\"",
    "\"|\"",
    "\"^\"",
    "\"&\"",
    "\"<<\"",
    "\">>\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"~\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<NULL>",
    "<TRUE>",
    "<FALSE>",
    "\"concat\"",
    "\"substring\"",
    "\"trim\"",
    "\"lower\"",
    "\"upper\"",
    "\"length\"",
    "\"locate\"",
    "\"abs\"",
    "\"sqrt\"",
    "\"mod\"",
    "\"currentDate\"",
    "\"currentTime\"",
    "<CURRENT_TIMESTAMP>",
    "\"year\"",
    "\"month\"",
    "\"week\"",
    "\"dayOfYear\"",
    "\"day\"",
    "\"dayOfMonth\"",
    "\"dayOfWeek\"",
    "\"hour\"",
    "\"minute\"",
    "\"second\"",
    "\"$\"",
    "<PROPERTY_PATH>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<DOLLAR_SIGN>",
    "\"\\\'\"",
    "\"\\\"\"",
    "<ESC>",
    "<token of kind 69>",
    "\"\\\'\"",
    "<STRING_ESC>",
    "<token of kind 72>",
    "\"\\\"\"",
    "<INT_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DEC_FLT>",
    "<DEC_DIGITS>",
    "<EXPONENT>",
    "<FLT_SUFF>",
  };

}
