/* Generated By:JavaCC: Do not edit this line. AgExpressionParserTreeConstants.java Version 7.0.11 */
package io.agrest.exp.parser;

public interface AgExpressionParserTreeConstants
{
  public int JJTROOT = 0;
  public int JJTVOID = 1;
  public int JJTOR = 2;
  public int JJTAND = 3;
  public int JJTNOT = 4;
  public int JJTTRUE = 5;
  public int JJTFALSE = 6;
  public int JJTEQUAL = 7;
  public int JJTNOTEQUAL = 8;
  public int JJTLESSOREQUAL = 9;
  public int JJTLESS = 10;
  public int JJTGREATER = 11;
  public int JJTGREATEROREQUAL = 12;
  public int JJTLIKE = 13;
  public int JJTLIKEIGNORECASE = 14;
  public int JJTIN = 15;
  public int JJTBETWEEN = 16;
  public int JJTNOTLIKE = 17;
  public int JJTNOTLIKEIGNORECASE = 18;
  public int JJTNOTIN = 19;
  public int JJTNOTBETWEEN = 20;
  public int JJTSCALARLIST = 21;
  public int JJTSCALARNULL = 22;
  public int JJTSCALARSTRING = 23;
  public int JJTSCALARBOOL = 24;
  public int JJTBITWISEOR = 25;
  public int JJTBITWISEXOR = 26;
  public int JJTBITWISEAND = 27;
  public int JJTBITWISELEFTSHIFT = 28;
  public int JJTBITWISERIGHTSHIFT = 29;
  public int JJTADD = 30;
  public int JJTSUBTRACT = 31;
  public int JJTMULTIPLY = 32;
  public int JJTDIVIDE = 33;
  public int JJTBITWISENOT = 34;
  public int JJTNEGATE = 35;
  public int JJTSCALARINT = 36;
  public int JJTSCALARFLOAT = 37;
  public int JJTCONCAT = 38;
  public int JJTSUBSTRING = 39;
  public int JJTTRIM = 40;
  public int JJTLOWER = 41;
  public int JJTUPPER = 42;
  public int JJTLENGTH = 43;
  public int JJTLOCATE = 44;
  public int JJTABS = 45;
  public int JJTSQRT = 46;
  public int JJTMOD = 47;
  public int JJTCURRENTDATE = 48;
  public int JJTCURRENTTIME = 49;
  public int JJTCURRENTTIMESTAMP = 50;
  public int JJTEXTRACT = 51;
  public int JJTNAMEDPARAMETER = 52;
  public int JJTOBJPATH = 53;


  public String[] jjtNodeName = {
    "Root",
    "void",
    "Or",
    "And",
    "Not",
    "True",
    "False",
    "Equal",
    "NotEqual",
    "LessOrEqual",
    "Less",
    "Greater",
    "GreaterOrEqual",
    "Like",
    "LikeIgnoreCase",
    "In",
    "Between",
    "NotLike",
    "NotLikeIgnoreCase",
    "NotIn",
    "NotBetween",
    "ScalarList",
    "ScalarNull",
    "ScalarString",
    "ScalarBool",
    "BitwiseOr",
    "BitwiseXor",
    "BitwiseAnd",
    "BitwiseLeftShift",
    "BitwiseRightShift",
    "Add",
    "Subtract",
    "Multiply",
    "Divide",
    "BitwiseNot",
    "Negate",
    "ScalarInt",
    "ScalarFloat",
    "Concat",
    "Substring",
    "Trim",
    "Lower",
    "Upper",
    "Length",
    "Locate",
    "Abs",
    "Sqrt",
    "Mod",
    "CurrentDate",
    "CurrentTime",
    "CurrentTimestamp",
    "Extract",
    "NamedParameter",
    "ObjPath",
  };
}
/* JavaCC - OriginalChecksum=22bc94b645caacf38b5f6161bc9ad9d4 (do not edit this line) */
