/* Generated By:JJTree: Do not edit this line. ExpBitwiseOr.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpBitwiseOr extends AgExpression {
  public ExpBitwiseOr(int id) {
    super(id);
  }

  public ExpBitwiseOr(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpBitwiseOr() {
    super(AgExpressionParserTreeConstants.JJTBITWISEOR);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpBitwiseOr();
  }

  @Override
  public String toString() {
    return "(" + children[0] + ") | (" + children[1] + ")";
  }
}
/* JavaCC - OriginalChecksum=9e655d2e49f2f89cbfc0290e3c55eaaa (do not edit this line) */
