/* Generated By:JJTree: Do not edit this line. ExpBitwiseAnd.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpBitwiseAnd extends SimpleNode {
  public ExpBitwiseAnd(int id) {
    super(id);
  }

  public ExpBitwiseAnd(AgExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=bedea5f1409689ecd029ecdf3598530f (do not edit this line) */
