/* Generated By:JJTree: Do not edit this line. ExpBitwiseRightShift.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpBitwiseRightShift extends SimpleNode {
  public ExpBitwiseRightShift(int id) {
    super(id);
  }

  public ExpBitwiseRightShift(AgExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=5cd02f3042da45f7de20ef87d820c299 (do not edit this line) */
