/* Generated By:JJTree: Do not edit this line. ExpBetween.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpBetween extends SimpleNode {
  public ExpBetween(int id) {
    super(id);
  }

  public ExpBetween(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpBetween() {
    super(AgExpressionParserTreeConstants.JJTBETWEEN);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected SimpleNode shallowCopy() {
    return new ExpBetween(id);
  }

  @Override
  public String toString() {
    return children != null
            ? children[0] + " between " + children[1] + " and " + children[2]
            : "? between ? and ?";
  }
}
/* JavaCC - OriginalChecksum=c43b74b247f96290e1207f5b0fcef774 (do not edit this line) */
