/* Generated By:JJTree: Do not edit this line. ExpBitwiseXor.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpBitwiseXor extends SimpleNode {
  public ExpBitwiseXor(int id) {
    super(id);
  }

  public ExpBitwiseXor(AgExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=336d0981f41ead75770ede0ffe57a1a6 (do not edit this line) */
