/* Generated By:JJTree: Do not edit this line. ExpCurrentDate.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpCurrentDate extends SimpleNode {
  public ExpCurrentDate(int id) {
    super(id);
  }

  public ExpCurrentDate(AgExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=11489a8212cd3fe2bb6f0452d8c139d3 (do not edit this line) */
