/* Generated By:JJTree: Do not edit this line. ExpCurrentTime.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpCurrentTime extends SimpleNode {
  public ExpCurrentTime(int id) {
    super(id);
  }

  public ExpCurrentTime(AgExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=453613d066bbd1eb7cfbd1e30f5b148d (do not edit this line) */
