/* Generated By:JJTree: Do not edit this line. ExpCurrentTimestamp.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpCurrentTimestamp extends AgExpression {
  public ExpCurrentTimestamp(int id) {
    super(id);
  }

  public ExpCurrentTimestamp(AgExpressionParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpCurrentTimestamp(id);
  }

  @Override
  public String toString() {
    return "currentTimestamp()";
  }
}
/* JavaCC - OriginalChecksum=c3ddadaa60478d01d051d9fd5b1f87c7 (do not edit this line) */
