/* Generated By:JJTree: Do not edit this line. ExpDivide.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpDivide extends AgExpression {
  public ExpDivide(int id) {
    super(id);
  }

  public ExpDivide(AgExpressionParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpDivide(id);
  }

  @Override
  public String toString() {
    return children[0] + " / " + children[1];
  }
}
/* JavaCC - OriginalChecksum=ff843f7912488202daf5cfaf1517956b (do not edit this line) */
