/* Generated By:JJTree: Do not edit this line. ExpIn.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpIn extends AgExpression {
  public ExpIn(int id) {
    super(id);
  }

  public ExpIn(AgExpressionParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpIn(id);
  }

  @Override
  public String toString() {
    return children[0] + " in " + (
            children[1].getClass() == ExpNamedParameter.class
                   ? children[1]
                   : "(" + children[1] + ")"
    );
  }
}
/* JavaCC - OriginalChecksum=40738702f4699c9b3a308d49a792f974 (do not edit this line) */
