/* Generated By:JJTree: Do not edit this line. ExpLess.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpLess extends AgExpression {
  public ExpLess(int id) {
    super(id);
  }

  public ExpLess(AgExpressionParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpLess(id);
  }

  @Override
  public String toString() {
    return "(" + children[0] + ") < (" + children[1] + ")";
  }
}
/* JavaCC - OriginalChecksum=cd3543ed8cbdcb8d8a299d020cc92831 (do not edit this line) */
