/* Generated By:JJTree: Do not edit this line. ExpLessOrEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpLessOrEqual extends SimpleNode {
  public ExpLessOrEqual(int id) {
    super(id);
  }

  public ExpLessOrEqual(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpLessOrEqual() {
    super(AgExpressionParserTreeConstants.JJTLESSOREQUAL);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected SimpleNode shallowCopy() {
    return new ExpLessOrEqual(id);
  }

  @Override
  public String toString() {
    return ExpStringConverter.convert(this);
  }
}
/* JavaCC - OriginalChecksum=0c80f493512f3c5d984682c830f7d9f1 (do not edit this line) */
