/* Generated By:JJTree: Do not edit this line. ExpLength.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpLength extends AgExpression {
  public ExpLength(int id) {
    super(id);
  }

  public ExpLength(AgExpressionParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpLength(id);
  }

  @Override
  public String toString() {
    return "length(" + children[0] + ")";
  }
}
/* JavaCC - OriginalChecksum=f19b92880659daa8634dd190871429c4 (do not edit this line) */
