/* Generated By:JJTree: Do not edit this line. ExpMultiply.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpMultiply extends AgExpression {
  public ExpMultiply(int id) {
    super(id);
  }

  public ExpMultiply(AgExpressionParser p, int id) {
    super(p, id);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpMultiply(id);
  }

  @Override
  public String toString() {
    return children[0] + " * " + children[1];
  }
}
/* JavaCC - OriginalChecksum=6ca0df20d086adb54be14cd41b93ed59 (do not edit this line) */
