/* Generated By:JJTree: Do not edit this line. ExpNotLikeIgnoreCase.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpNotLikeIgnoreCase extends SimpleNode {
  public ExpNotLikeIgnoreCase(int id) {
    super(id);
  }

  public ExpNotLikeIgnoreCase(AgExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f691866512a95995b0af48e8ae28f7e7 (do not edit this line) */
