/* Generated By:JJTree: Do not edit this line. ExpNotExists.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.protocol.Exp;

public
class ExpNotExists extends SimpleNode {
  public ExpNotExists(int id) {
    super(id);
  }

  public ExpNotExists(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpNotExists() {
    super(AgExpressionParser.JJTNOTEXISTS);
  }

  public ExpNotExists(String subExp) {
    this();
    children = new Node[] {(Node) Exp.parse(subExp)};
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected SimpleNode shallowCopy() {
    return new ExpNotExists(id);
  }

  @Override
  public String toString() {
    return ExpStringConverter.convert(this);
  }
}
/* JavaCC - OriginalChecksum=03cd7248945849bc19c8893523f8c916 (do not edit this line) */
