/* Generated By:JJTree: Do not edit this line. ExpNotEqual.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpNotEqual extends SimpleNode {
  public ExpNotEqual(int id) {
    super(id);
  }

  public ExpNotEqual(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpNotEqual() {
    super(AgExpressionParserTreeConstants.JJTNOTEQUAL);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  // TODO: override not() to compact the result

  @Override
  protected ExpNotEqual shallowCopy() {
    return new ExpNotEqual(id);
  }

  @Override
  public String toString() {
    return children != null
            ? "(" + children[0] + ") != (" + children[1] + ")"
            : "? != ?";
  }
}
/* JavaCC - OriginalChecksum=cd31a8834ec599e6eb06535df7a2b157 (do not edit this line) */
