/* Generated By:JJTree: Do not edit this line. ExpNegate.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpNegate extends SimpleNode {
  public ExpNegate(int id) {
    super(id);
  }

  public ExpNegate(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpNegate() {
    super(AgExpressionParserTreeConstants.JJTNEGATE);
  }

  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected SimpleNode shallowCopy() {
    return new ExpNegate(id);
  }

  @Override
  public String toString() {
    return ExpStringConverter.convert(this);
  }
}
/* JavaCC - OriginalChecksum=100942f12f6576bdafd2b6051325e733 (do not edit this line) */
