/* Generated By:JJTree: Do not edit this line. ExpScalarString.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public class ExpScalarString extends ExpScalar<String> {
    public ExpScalarString(int id) {
        super(id);
    }

    public ExpScalarString(AgExpressionParser p, int id) {
        super(p, id);
    }


    /**
     * Accept the visitor.
     **/
    public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {
        return visitor.visit(this, data);
    }
}
/* JavaCC - OriginalChecksum=4c0d3d45a2d8b347336ffc0b9a97795f (do not edit this line) */
