/* Generated By:JJTree: Do not edit this line. ExpSubtract.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

public
class ExpSubtract extends SimpleNode {
  public ExpSubtract(int id) {
    super(id);
  }

  public ExpSubtract(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpSubtract() {
    super(AgExpressionParserTreeConstants.JJTSUBTRACT);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected ExpSubtract shallowCopy() {
    return new ExpSubtract(id);
  }

  @Override
  public String toString() {
    return ExpStringConverter.convert(this);
  }
}
/* JavaCC - OriginalChecksum=9461ebb6e8a7eebd514bd15e14ac0623 (do not edit this line) */
