/* Generated By:JJTree: Do not edit this line. ExpSubstring.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=Exp,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.exp.parser;

import io.agrest.exp.AgExpression;

public
class ExpSubstring extends AgExpression {
  public ExpSubstring(int id) {
    super(id);
  }

  public ExpSubstring(AgExpressionParser p, int id) {
    super(p, id);
  }

  public ExpSubstring() {
    super(AgExpressionParserTreeConstants.JJTSUBSTRING);
  }


  /** Accept the visitor. **/
  public <T> T jjtAccept(AgExpressionParserVisitor<T> visitor, T data) {

    return
    visitor.visit(this, data);
  }

  @Override
  protected AgExpression shallowCopy() {
    return new ExpSubtract(id);
  }

  @Override
  public String toString() {
    return "substring(" + children[0] + ", " + children[1] + (children.length > 2 ? ", " + children[2] : "") + ")";
  }
}
/* JavaCC - OriginalChecksum=b4242b007471c91ebcaa890a9eac531d (do not edit this line) */
