== Non-Persistent Properties and POJOs

Agrest maintains a model of all entities that can be exposed via REST. All persistent
entities present in the underlying ORM (usually Cayenne) are automatically added to Agrest
model. What if you want to expose additional non-persistent properties of peristent objects or
build entire request chains that are not based on persistent entities? There are three
annotations to help with it: `@AgAttribute` or `@AgRelationship` and `@AgId`.

The first example is a typical Cayenne persistent class that has some transient properties:

[source, Java]
----
import io.agrest.annotation.AgAttribute;

// a typical Cayenne persistent class
public class Domain extends _Domain {

  @AgAttribute
  public String getLowercaseName() {
    return getName().toLowerCase();
  }
}
----

This one was simple. The second example is an entire POJO not known to Cayenne:

[source, Java]
----
import io.agrest.annotation.AgAttribute;
import io.agrest.annotation.AgRelationship;

// a POJO not mapped in Cayenne
public class SomeClass {

  private int id;
  private String string;
  private SomeOtherClass related;

  @AgId
  public int getId() {
    return id;
  }

  @AgAttribute
  public String getString() {
    return string;
  }

  @AgRelationship
  public SomeOtherClass getRelated() {
    return related;
  }
}
----

Creating and annotating a POJO was easy. But Agrest still requires a backend that knows
how to select and/or update those POJOs. Such custom "backends" can be configured per request
chain using chain listener API. It is up to the caller what strategy the backend would utilize
(maybe a REST call, or reading/writing from a NoSQL DB, etc.) :


[source, Java]
----
// an object with methods annotated with one of the
// 'io.agrest.annotation.listener' annotations
SomeCustomBackend altBackend = new SomeCustomBackend();

Ag.select(SomeClass.class, config).listener(altBackend).uri(urlInfo).get();
----