package com.nhl.link.rest.unit.cayenne.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.nhl.link.rest.unit.cayenne.E12;
import com.nhl.link.rest.unit.cayenne.E13;

/**
 * Class _E12E13 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E12E13 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    @Deprecated
    public static final String E12_PROPERTY = "e12";
    @Deprecated
    public static final String E13_PROPERTY = "e13";

    public static final String E12_ID_PK_COLUMN = "e12_id";
    public static final String E13_ID_PK_COLUMN = "e13_id";

    public static final Property<E12> E12 = new Property<E12>("e12");
    public static final Property<E13> E13 = new Property<E13>("e13");

    public void setE12(E12 e12) {
        setToOneTarget("e12", e12, true);
    }

    public E12 getE12() {
        return (E12)readProperty("e12");
    }


    public void setE13(E13 e13) {
        setToOneTarget("e13", e13, true);
    }

    public E13 getE13() {
        return (E13)readProperty("e13");
    }


}
