package io.agrest.cayenne.cayenne.main.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.agrest.cayenne.cayenne.main.E15E1;

/**
 * Class _E1 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E1 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Integer> AGE = Property.create("age", Integer.class);
    public static final Property<String> DESCRIPTION = Property.create("description", String.class);
    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<E15E1>> E15E1 = Property.create("e15e1", List.class);

    public void setAge(Integer age) {
        writeProperty("age", age);
    }
    public Integer getAge() {
        return (Integer)readProperty("age");
    }

    public void setDescription(String description) {
        writeProperty("description", description);
    }
    public String getDescription() {
        return (String)readProperty("description");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToE15e1(E15E1 obj) {
        addToManyTarget("e15e1", obj, true);
    }
    public void removeFromE15e1(E15E1 obj) {
        removeToManyTarget("e15e1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E15E1> getE15e1() {
        return (List<E15E1>)readProperty("e15e1");
    }


}
