package io.agrest.cayenne.cayenne.main.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.property.ListProperty;
import org.apache.cayenne.exp.property.NumericProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.StringProperty;

import io.agrest.cayenne.cayenne.main.E18;

/**
 * Class _E17 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E17 extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID1_PK_COLUMN = "id1";
    public static final String ID2_PK_COLUMN = "id2";

    public static final NumericProperty<Integer> ID1 = PropertyFactory.createNumeric("id1", Integer.class);
    public static final NumericProperty<Integer> ID2 = PropertyFactory.createNumeric("id2", Integer.class);
    public static final StringProperty<String> NAME = PropertyFactory.createString("name", String.class);
    public static final ListProperty<E18> E18S = PropertyFactory.createList("e18s", E18.class);

    protected Integer id1;
    protected Integer id2;
    protected String name;

    protected Object e18s;

    public void setId1(Integer id1) {
        beforePropertyWrite("id1", this.id1, id1);
        this.id1 = id1;
    }

    public Integer getId1() {
        beforePropertyRead("id1");
        return this.id1;
    }

    public void setId2(Integer id2) {
        beforePropertyWrite("id2", this.id2, id2);
        this.id2 = id2;
    }

    public Integer getId2() {
        beforePropertyRead("id2");
        return this.id2;
    }

    public void setName(String name) {
        beforePropertyWrite("name", this.name, name);
        this.name = name;
    }

    public String getName() {
        beforePropertyRead("name");
        return this.name;
    }

    public void addToE18s(E18 obj) {
        addToManyTarget("e18s", obj, true);
    }

    public void removeFromE18s(E18 obj) {
        removeToManyTarget("e18s", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<E18> getE18s() {
        return (List<E18>)readProperty("e18s");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "id1":
                return this.id1;
            case "id2":
                return this.id2;
            case "name":
                return this.name;
            case "e18s":
                return this.e18s;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "id1":
                this.id1 = (Integer)val;
                break;
            case "id2":
                this.id2 = (Integer)val;
                break;
            case "name":
                this.name = (String)val;
                break;
            case "e18s":
                this.e18s = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.id1);
        out.writeObject(this.id2);
        out.writeObject(this.name);
        out.writeObject(this.e18s);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.id1 = (Integer)in.readObject();
        this.id2 = (Integer)in.readObject();
        this.name = (String)in.readObject();
        this.e18s = in.readObject();
    }

}
