package io.agrest.cayenne.cayenne.main.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;

import org.apache.cayenne.PersistentObject;
import org.apache.cayenne.exp.property.BaseProperty;
import org.apache.cayenne.exp.property.PropertyFactory;
import org.apache.cayenne.exp.property.SelfProperty;
import org.apache.cayenne.value.Json;

import io.agrest.cayenne.cayenne.main.E28;

/**
 * Class _E28 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E28 extends PersistentObject {

    private static final long serialVersionUID = 1L;

    public static final SelfProperty<E28> SELF = PropertyFactory.createSelf(E28.class);

    public static final String ID_PK_COLUMN = "id";

    public static final BaseProperty<Json> JSON = PropertyFactory.createBase("json", Json.class);

    protected Json json;


    public void setJson(Json json) {
        beforePropertyWrite("json", this.json, json);
        this.json = json;
    }

    public Json getJson() {
        beforePropertyRead("json");
        return this.json;
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "json":
                return this.json;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "json":
                this.json = (Json)val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.json);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.json = (Json)in.readObject();
    }

}
