package io.agrest.cayenne.cayenne.main.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _E28 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E28 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID1_PK_COLUMN = "ID1";
    public static final String ID2_PK_COLUMN = "ID2";

    public static final Property<Integer> ID2PROP = Property.create("id2Prop", Integer.class);

    public void setId2Prop(Integer id2Prop) {
        writeProperty("id2Prop", id2Prop);
    }
    public Integer getId2Prop() {
        return (Integer)readProperty("id2Prop");
    }

}
