package io.agrest.cayenne.cayenne.main.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import io.agrest.cayenne.cayenne.main.E2;
import io.agrest.cayenne.cayenne.main.E5;

/**
 * Class _E3 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E3 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID__PK_COLUMN = "id_";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<String> PHONE_NUMBER = Property.create("phoneNumber", String.class);
    public static final Property<E2> E2 = Property.create("e2", E2.class);
    public static final Property<E5> E5 = Property.create("e5", E5.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void setPhoneNumber(String phoneNumber) {
        writeProperty("phoneNumber", phoneNumber);
    }
    public String getPhoneNumber() {
        return (String)readProperty("phoneNumber");
    }

    public void setE2(E2 e2) {
        setToOneTarget("e2", e2, true);
    }

    public E2 getE2() {
        return (E2)readProperty("e2");
    }


    public void setE5(E5 e5) {
        setToOneTarget("e5", e5, true);
    }

    public E5 getE5() {
        return (E5)readProperty("e5");
    }


}
