package com.nhl.link.rest.it.fixture.cayenne.auto;

import java.sql.Date;
import java.sql.Time;
import java.sql.Timestamp;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _E16 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E16 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Date> C_DATE = new Property<Date>("cDate");
    public static final Property<Time> C_TIME = new Property<Time>("cTime");
    public static final Property<Timestamp> C_TIMESTAMP = new Property<Timestamp>("cTimestamp");

    public void setCDate(Date cDate) {
        writeProperty("cDate", cDate);
    }
    public Date getCDate() {
        return (Date)readProperty("cDate");
    }

    public void setCTime(Time cTime) {
        writeProperty("cTime", cTime);
    }
    public Time getCTime() {
        return (Time)readProperty("cTime");
    }

    public void setCTimestamp(Timestamp cTimestamp) {
        writeProperty("cTimestamp", cTimestamp);
    }
    public Timestamp getCTimestamp() {
        return (Timestamp)readProperty("cTimestamp");
    }

}
