package com.nhl.link.rest.it.fixture.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.nhl.link.rest.it.fixture.cayenne.E18;

/**
 * Class _E17 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E17 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID1_PK_COLUMN = "id1";
    public static final String ID2_PK_COLUMN = "id2";

    public static final Property<Integer> ID1 = new Property<Integer>("id1");
    public static final Property<Integer> ID2 = new Property<Integer>("id2");
    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<E18>> E18S = new Property<List<E18>>("e18s");

    public void setId1(Integer id1) {
        writeProperty("id1", id1);
    }
    public Integer getId1() {
        return (Integer)readProperty("id1");
    }

    public void setId2(Integer id2) {
        writeProperty("id2", id2);
    }
    public Integer getId2() {
        return (Integer)readProperty("id2");
    }

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToE18s(E18 obj) {
        addToManyTarget("e18s", obj, true);
    }
    public void removeFromE18s(E18 obj) {
        removeToManyTarget("e18s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E18> getE18s() {
        return (List<E18>)readProperty("e18s");
    }


}
