package com.nhl.link.rest.it.fixture.cayenne.auto;

import java.math.BigDecimal;
import java.util.Date;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _E4 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E4 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<Boolean> C_BOOLEAN = Property.create("cBoolean", Boolean.class);
    public static final Property<Date> C_DATE = Property.create("cDate", Date.class);
    public static final Property<BigDecimal> C_DECIMAL = Property.create("cDecimal", BigDecimal.class);
    public static final Property<Integer> C_INT = Property.create("cInt", Integer.class);
    public static final Property<Date> C_TIME = Property.create("cTime", Date.class);
    public static final Property<Date> C_TIMESTAMP = Property.create("cTimestamp", Date.class);
    public static final Property<String> C_VARCHAR = Property.create("cVarchar", String.class);

    public void setCBoolean(Boolean cBoolean) {
        writeProperty("cBoolean", cBoolean);
    }
    public Boolean getCBoolean() {
        return (Boolean)readProperty("cBoolean");
    }

    public void setCDate(Date cDate) {
        writeProperty("cDate", cDate);
    }
    public Date getCDate() {
        return (Date)readProperty("cDate");
    }

    public void setCDecimal(BigDecimal cDecimal) {
        writeProperty("cDecimal", cDecimal);
    }
    public BigDecimal getCDecimal() {
        return (BigDecimal)readProperty("cDecimal");
    }

    public void setCInt(Integer cInt) {
        writeProperty("cInt", cInt);
    }
    public Integer getCInt() {
        return (Integer)readProperty("cInt");
    }

    public void setCTime(Date cTime) {
        writeProperty("cTime", cTime);
    }
    public Date getCTime() {
        return (Date)readProperty("cTime");
    }

    public void setCTimestamp(Date cTimestamp) {
        writeProperty("cTimestamp", cTimestamp);
    }
    public Date getCTimestamp() {
        return (Date)readProperty("cTimestamp");
    }

    public void setCVarchar(String cVarchar) {
        writeProperty("cVarchar", cVarchar);
    }
    public String getCVarchar() {
        return (String)readProperty("cVarchar");
    }

}
