=== Strategies for Object Matching

Many of the updating chains need to match objects coming as Update Documents (see <<Request: Update Document>>) against
objects in the database. E.g. "createOrUpdate" needs to know whether a JSON object is new (and needs to be created)
or it already exists (and needs to be updated). By default AgREST would attempt to match each JSON
"id" attribute with a DB record primary key. This is a reasonable and useful strategy. Its
main limitation though - it can't be used for entities with ids generated on the server when
combined with idempotent requests (see the next section on idempotency). To work around this
limitation one may use a meaningful unique property that is known to the client at the object
creation time. E.g. our Domain entity has a unique property "vhost".

To ensure the chain uses a property other than "id" for matching, a user may should set an
explicit mapper on the chain:

[source, Java]
----
AgREST.idempotentCreateOrUpdate(Domain.class, config)
      .mapper(ByKeyObjectMapperFactory.byKey(Domain.VHOST))
      .sync(entityData);
----

`ByKeyObjectMapperFactory` mapper is provided by AgREST. If something other than mapping by property is needed, a
 custom `ObjectMapperFactory` can be coded by the user.