package com.nhl.link.rest.it.fixture.cayenne.iso.auto;

import java.sql.Time;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

/**
 * Class _ISOTimeTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ISOTimeTestEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Time> TIME = Property.create("time", Time.class);

    public void setTime(Time time) {
        writeProperty("time", time);
    }
    public Time getTime() {
        return (Time)readProperty("time");
    }

}
