package com.nhl.link.rest.it.fixture.cayenne.iso.auto;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import java.sql.Date;

/**
 * Class _ISODateTestEntity was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _ISODateTestEntity extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Date> SQL_DATE = new Property<Date>("sqlDate");
    public static final Property<java.util.Date> UTIL_DATE = new Property<java.util.Date>("utilDate");

    public void setSqlDate(Date sqlDate) {
        writeProperty("sqlDate", sqlDate);
    }
    public Date getSqlDate() {
        return (Date)readProperty("sqlDate");
    }

    public void setUtilDate(java.util.Date utilDate) {
        writeProperty("utilDate", utilDate);
    }
    public java.util.Date getUtilDate() {
        return (java.util.Date)readProperty("utilDate");
    }

}
