/* Generated By:JJTree: Do not edit this line. ASTAbs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTAbs extends ASTFunctionCall {

    public ASTAbs(int id) {
        super(id, "ABS");
    }

    public ASTAbs(Expression expression) {
        super(ExpressionParserTreeConstants.JJTABS, "ABS", expression);
    }


    @Override
    public Expression shallowCopy() {
        return new ASTAbs(id);
    }
}
/* JavaCC - OriginalChecksum=a802a2a7174fcccf21135e8998d5cc27 (do not edit this line) */
