/* Generated By:JJTree: Do not edit this line. ASTAbs.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTAbs extends SimpleNode {
  public ASTAbs(int id) {
    super(id);
  }

  public ASTAbs(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=a802a2a7174fcccf21135e8998d5cc27 (do not edit this line) */
