/* Generated By:JJTree: Do not edit this line. ASTAdd.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTAdd extends SimpleNode {

    ASTAdd(int id) {
        super(id);
    }

    public ASTAdd() {
        super(ExpressionParserTreeConstants.JJTADD);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTAdd(id);
    }
}
/* JavaCC - OriginalChecksum=3ed1603c6e2ec221dca29564c8d2c62e (do not edit this line) */
