/* Generated By:JJTree: Do not edit this line. ASTBitwiseLeftShift.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTBitwiseLeftShift extends SimpleNode {
    public ASTBitwiseLeftShift(int id) {
        super(id);
    }

    public ASTBitwiseLeftShift() {
        super(ExpressionParserTreeConstants.JJTBITWISELEFTSHIFT);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTBitwiseLeftShift(id);
    }
}
/* JavaCC - OriginalChecksum=878ca9863ed903c37b1e95b463768ac6 (do not edit this line) */
