/* Generated By:JJTree: Do not edit this line. ASTBetween.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

/**
 * "Between" expression.
 */
public class ASTBetween extends ConditionNode {

    public ASTBetween(int id) {
        super(id);
    }

    public ASTBetween() {
        super(ExpressionParserTreeConstants.JJTBETWEEN);
    }

    public ASTBetween(SimpleNode path, Object value1, Object value2) {
        super(ExpressionParserTreeConstants.JJTBETWEEN);
        jjtAddChild(path, 0);
        jjtAddChild(new ASTScalar(value1), 1);
        jjtAddChild(new ASTScalar(value2), 2);

        connectChildren();
    }

    @Override
    public Expression shallowCopy() {
        return new ASTBetween(id);
    }

    @Override
    public int getType() {
        return Expression.BETWEEN;
    }

}
/* JavaCC - OriginalChecksum=7df505698c123de56f954f06b12be9ab (do not edit this line) */
