/* Generated By:JJTree: Do not edit this line. ASTConcat.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTConcat extends SimpleNode {
  public ASTConcat(int id) {
    super(id);
  }

  public ASTConcat(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fbee74fcba9d176fed00e7314acc36a3 (do not edit this line) */
