/* Generated By:JJTree: Do not edit this line. ASTCurrentTimestamp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTCurrentTimestamp extends SimpleNode {
  public ASTCurrentTimestamp(int id) {
    super(id);
  }

  public ASTCurrentTimestamp(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b31fd04bc6070c3c4e6e3102777fa088 (do not edit this line) */
