/* Generated By:JJTree: Do not edit this line. ASTDbPath.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTDbPath extends ASTPath {

    public static final String DB_PREFIX = "db:";

    public ASTDbPath(int id) {
        super(id);
    }

    public ASTDbPath() {
        super(ExpressionParserTreeConstants.JJTDBPATH);
    }

    public ASTDbPath(Object value) {
        super(ExpressionParserTreeConstants.JJTDBPATH);
        setPath(value);
    }

    /**
     * Creates a copy of this expression node, without copying children.
     */
    @Override
    public Expression shallowCopy() {
        ASTDbPath copy = new ASTDbPath(id);
        copy.path = path;
        return copy;
    }

    @Override
    public String toString() {
        return DB_PREFIX + path;
    }
}
/* JavaCC - OriginalChecksum=f6b74d4b5dd8475109499d882651802a (do not edit this line) */
