/* Generated By:JJTree: Do not edit this line. ASTEnum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import org.apache.cayenne.exp.ExpressionException;
import org.apache.cayenne.exp.ExpressionParameter;
import org.apache.cayenne.exp.parser.ASTScalar;

public
class ASTEnum extends ASTScalar {
  public ASTEnum(int id) {
    super(id);
  }

//  public ASTEnum(ExpressionParser p, int id) {
//    super(p, id);
//  }

}
/* JavaCC - OriginalChecksum=c8ccffb962b40fa4cf19e2d922466988 (do not edit this line) */
