/* Generated By:JJTree: Do not edit this line. ASTExtract.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTExtract extends SimpleNode {
  public ASTExtract(int id) {
    super(id);
  }

  public ASTExtract(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=c0a8e9c96cae8eaa1732c88d58dbbefa (do not edit this line) */
