/* Generated By:JJTree: Do not edit this line. ASTGreater.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

/**
 * "Greater Than" expression.
 */
public class ASTGreater extends ConditionNode {

    /**
     * Constructor used by expression parser. Do not invoke directly.
     */
    ASTGreater(int id) {
        super(id);
    }

    public ASTGreater() {
        super(ExpressionParserTreeConstants.JJTGREATER);
    }

    public ASTGreater(SimpleNode path, Object value) {
        super(ExpressionParserTreeConstants.JJTGREATER);
        jjtAddChild(path, 0);
        jjtAddChild(new ASTScalar(value), 1);
        connectChildren();
    }

    @Override
    public Expression shallowCopy() {
        return new ASTGreater(id);
    }

    @Override
    public int getType() {
        return Expression.GREATER_THAN;
    }

}
/* JavaCC - OriginalChecksum=b5edb65e77757d0c765b86a9aa88717c (do not edit this line) */
