/* Generated By:JJTree: Do not edit this line. ASTLikeIgnoreCase.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTLikeIgnoreCase extends SimpleNode {
  public ASTLikeIgnoreCase(int id) {
    super(id);
  }

  public ASTLikeIgnoreCase(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=8e8d020d228b3cf00e4bff3c7ed6015d (do not edit this line) */
