/* Generated By:JJTree: Do not edit this line. ASTLower.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTLower extends ASTFunctionCall {


    ASTLower(int id) {
        super(id, "LOWER");
    }

    public ASTLower(Expression expression) {
        super(ExpressionParserTreeConstants.JJTLOWER, "LOWER", expression);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTLower(id);
    }
}
/* JavaCC - OriginalChecksum=ffc6504ce2a4f8e2fa58a8a780609e4f (do not edit this line) */
