/* Generated By:JJTree: Do not edit this line. ASTLike.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTLike extends SimpleNode {
  public ASTLike(int id) {
    super(id);
  }

  public ASTLike(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=d7026b92b15023fdd0aa96691aed3849 (do not edit this line) */
