/* Generated By:JJTree: Do not edit this line. ASTLocate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTLocate extends SimpleNode {
  public ASTLocate(int id) {
    super(id);
  }

  public ASTLocate(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=82768593d1a43eda62c875d09bc1148a (do not edit this line) */
