/* Generated By:JJTree: Do not edit this line. ASTMax.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTMax extends SimpleNode {
  public ASTMax(int id) {
    super(id);
  }

  public ASTMax(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=b3e15fb0fdad413a0e23eb2a2beaa9ad (do not edit this line) */
