/* Generated By:JJTree: Do not edit this line. ASTMod.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTMod extends ASTFunctionCall {

    ASTMod(int id) {
        super(id, "MOD");
    }

    public ASTMod(Expression expression, Expression divisor) {
        super(ExpressionParserTreeConstants.JJTMOD, "MOD", expression, divisor);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTMod(id);
    }
}
/* JavaCC - OriginalChecksum=e9e367fcf78e772b3a3a5923f54c399f (do not edit this line) */
