/* Generated By:JJTree: Do not edit this line. ASTNotLikeIgnoreCase.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

public
class ASTNotLikeIgnoreCase extends SimpleNode {
  public ASTNotLikeIgnoreCase(int id) {
    super(id);
  }

  public ASTNotLikeIgnoreCase(ExpressionParser p, int id) {
    super(p, id);
  }

}
/* JavaCC - OriginalChecksum=fb6fa62dfcb4757c14cb3fc5536b0779 (do not edit this line) */
