/* Generated By:JJTree: Do not edit this line. ASTNot.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTNot extends SimpleNode {
    public ASTNot(int id) {
        super(id);
    }

    public ASTNot(ExpressionParser p, int id) {
        super(p, id);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTNot(id);
    }
}
/* JavaCC - OriginalChecksum=b89178142e4818b840ce26d8c61a3723 (do not edit this line) */
