/* Generated By:JJTree: Do not edit this line. ASTNegate.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTNegate extends SimpleNode {
    public ASTNegate(int id) {
        super(id);
    }

    public ASTNegate() {
        super(ExpressionParserTreeConstants.JJTNEGATE);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTNegate(id);
    }
}
/* JavaCC - OriginalChecksum=534e1239e87f5d68165e31da6019c615 (do not edit this line) */
