/* Generated By:JJTree: Do not edit this line. ASTNamedParameter.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import org.apache.cayenne.exp.ExpressionException;
import org.apache.cayenne.exp.ExpressionParameter;
import org.apache.cayenne.exp.parser.ASTScalar;

public
class ASTNamedParameter extends ASTScalar {
  public ASTNamedParameter(int id) {
    super(id);
  }

//  public ASTNamedParameter(ExpressionParser p, int id) {
//    super(p, id);
//  }

    @Override
    public void setValue(Object value) {
        if (value == null) {
            throw new ExpressionException("Null Parameter value");
        }

        String name = value.toString().trim();
        if (name.length() == 0) {
            throw new ExpressionException("Empty Parameter value");
        }

        super.setValue(new ExpressionParameter(name));
    }


}
/* JavaCC - OriginalChecksum=2401c5d2502f53b9f1066bb5217108fc (do not edit this line) */
