/* Generated By:JJTree: Do not edit this line. ASTSum.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTSum extends SimpleNode {
    public ASTSum(int id) {
        super(id);
    }

    public ASTSum(ExpressionParser p, int id) {
        super(p, id);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTSum(id);
    }
}
/* JavaCC - OriginalChecksum=d4eecad1d8c6a0870b62e208d432cfcd (do not edit this line) */
