/* Generated By:JJTree: Do not edit this line. ASTTrim.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTTrim extends ASTFunctionCall {

    ASTTrim(int id) {
        super(id, "TRIM");
    }

    public ASTTrim(Expression path) {
        super(ExpressionParserTreeConstants.JJTTRIM, "TRIM", path);
    }

    @Override
    public int getType() {
        return Expression.FUNCTION_CALL;
    }

    @Override
    public Expression shallowCopy() {
        return new ASTTrim(id);
    }
}
/* JavaCC - OriginalChecksum=67bc692f006394c7292b2857740d6e15 (do not edit this line) */
