/* Generated By:JJTree: Do not edit this line. ASTUpper.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=false,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package io.agrest.backend.exp.parser;

import io.agrest.backend.exp.Expression;

public class ASTUpper extends SimpleNode {
    public ASTUpper(int id) {
        super(id);
    }

    public ASTUpper(ExpressionParser p, int id) {
        super(p, id);
    }

    @Override
    public Expression shallowCopy() {
        return new ASTUpper(id);
    }
}
/* JavaCC - OriginalChecksum=67f927eebcaf099a6b2873314cf2b169 (do not edit this line) */
