=== Shaping Collection with `include / exclude`

Model entities may have "simple" properties (attributes) and properties that point to
related entities (relationships). By default Collection Document contains entity
representation that includes its "id", all of its attributes, and none of the
relationships. "include" and "exclude" parameters allow the client to request a specific
subset of entity properties, including related entities. Some examples are given below,
showing include/exclude parameters and resulting entity contents.

Example 1: Include default properties (all entity attributes) minus "vhost" attribute.

`exclude=vhost`

[source, JSON]
----
{ "id" : 45, "name" : "Agrest Site" }
----

Example 2: Exclude all properties, but "id".

`include=id`

[source, JSON]
----
{ "id" : 45 }
----

Example 3: Multiple includes, one of them points to attributes of related entity.

`include=id&amp;include=articles.title`

[source, JSON]
----
{
   "id" : 45,
   "articles" : [
      { "title" : "Agrest Includes" },
      { "title" : "Other Tech News" },
      { "title" : "Introducing Agrest" }
   ]
}
----

Example 4: Advanced include. Include specification can itself be a JSON object and
contain `"exp"`, `"sort"`, `"start"` and `"limit"` keys shaping up a collection
of related objects for each root object.

`include={"path":"articles","exp":"title like '%Agrest%'","sort":"title"}&amp;include=articles.title`

[source, JSON]
----
{
   "id" : 45,
   "articles" : [
      { "title" : "Introducing Agrest" },
      { "title" : "Agrest Includes" }
   ]
}
----

NOTE: "exp" key was first introduced in Agrest 4.1. Previously it was called "cayenneExp".
Both are synonymous. "cayenneExp" is still supported, though should be considered deprecated.

Example 5: Related objects as a map. Here we'll map article bodies by title.

`include={"path":"articles","mapBy":"title"}&amp;include=articles.body`

[source, JSON]
----
{
   "articles" : {
      "Introducing Agrest" : { "body" : "Agrest is a .." },
      "Agrest Includes" : { "body" : "Includes are .." }
   }
}
----

Example 6: Include and Exclude parameters have ability to take an array of values:

`include=["id","name"]`

[source, JSON]
----
{ "id" : 45, "name" : "Agrest Site" }
----

Example 7: The array can contain both the simple include and the advanced include values

`include=["id","articles.title",{"path":"articles","exp":"title like '%Agrest%'"}]`

[source, JSON]
----
{
   "id" : 45,
   "articles" : [
      { "title" : "Introducing Agrest" },
      { "title" : "Agrest Includes" }
   ]
}
----

Example 8: Attributes of a related entity can be presented as an inner array in JSON format:

`include=["id","name",{"articles":["title","body"]}]`

[source, JSON]
----
{
   "id" : 45,
   "name" : "Agrest Site",
   "articles" : [
      { "title" : "Introducing Agrest", "body" : "Agrest is a .." },
      { "title" : "Agrest Includes", "body" : "Includes are .." }
   ]
}
----

Example 9: The related entity can be specified as a path value:

`include=["id","name",{"articles.categories":["id","name"]}]`

Example 10: The advanced include can contain the array of include values:

`include={"path":"articles","sort":"title","include":["title",{"categories":["id","name"]}]}`
