package com.nhl.link.rest.it.fixture.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.nhl.link.rest.it.fixture.cayenne.E14;
import com.nhl.link.rest.it.fixture.cayenne.E15E1;
import com.nhl.link.rest.it.fixture.cayenne.E5;

/**
 * Class _E15 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E15 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String LONG_ID_PK_COLUMN = "long_id";

    public static final Property<String> NAME = Property.create("name", String.class);
    public static final Property<List<E14>> E14S = Property.create("e14s", List.class);
    public static final Property<List<E15E1>> E15E1 = Property.create("e15e1", List.class);
    public static final Property<List<E5>> E5S = Property.create("e5s", List.class);

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToE14s(E14 obj) {
        addToManyTarget("e14s", obj, true);
    }
    public void removeFromE14s(E14 obj) {
        removeToManyTarget("e14s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E14> getE14s() {
        return (List<E14>)readProperty("e14s");
    }


    public void addToE15e1(E15E1 obj) {
        addToManyTarget("e15e1", obj, true);
    }
    public void removeFromE15e1(E15E1 obj) {
        removeToManyTarget("e15e1", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E15E1> getE15e1() {
        return (List<E15E1>)readProperty("e15e1");
    }


    public void addToE5s(E5 obj) {
        addToManyTarget("e5s", obj, true);
    }
    public void removeFromE5s(E5 obj) {
        removeToManyTarget("e5s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E5> getE5s() {
        return (List<E5>)readProperty("e5s");
    }


}
