package com.nhl.link.rest.it.fixture.cayenne.auto;

import java.util.List;

import org.apache.cayenne.CayenneDataObject;
import org.apache.cayenne.exp.Property;

import com.nhl.link.rest.it.fixture.cayenne.E7;
import com.nhl.link.rest.it.fixture.cayenne.E9;

/**
 * Class _E8 was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _E8 extends CayenneDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "id";

    public static final Property<String> NAME = new Property<String>("name");
    public static final Property<List<E7>> E7S = new Property<List<E7>>("e7s");
    public static final Property<E9> E9 = new Property<E9>("e9");

    public void setName(String name) {
        writeProperty("name", name);
    }
    public String getName() {
        return (String)readProperty("name");
    }

    public void addToE7s(E7 obj) {
        addToManyTarget("e7s", obj, true);
    }
    public void removeFromE7s(E7 obj) {
        removeToManyTarget("e7s", obj, true);
    }
    @SuppressWarnings("unchecked")
    public List<E7> getE7s() {
        return (List<E7>)readProperty("e7s");
    }


    public void setE9(E9 e9) {
        setToOneTarget("e9", e9, true);
    }

    public E9 getE9() {
        return (E9)readProperty("e9");
    }


}
