name: 'build test deploy'

on: pull_request

jobs:
  verify:
    runs-on: ubuntu-latest
    if: github.repository == 'agrestio/agrest'

    name: JDK ${{ matrix.java }}

    strategy:
      matrix:
        java: [ "11", "17", "21" ]
      fail-fast: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.jdk }}
          cache: 'maven'

      - name: Build and test...
        run: mvn clean verify